services:
  - type: web
    name: stock-management-site
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ORACLE_USER
        sync: false
      - key: ORACLE_PASSWORD
        sync: false
      - key: ORACLE_DSN
        sync: false
