CREATE TABLE app_users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(255),
    email VARCHAR2(255),
    login_method VARCHAR2(30) DEFAULT 'local' NOT NULL,
    role VARCHAR2(30) DEFAULT 'user' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(150) NOT NULL,
    category VARCHAR2(100) NOT NULL,
    price NUMBER(10, 2) DEFAULT 0 NOT NULL,
    quantity NUMBER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sales (
    sale_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    sale_date DATE DEFAULT SYSDATE,
    total_amount NUMBER(12, 2) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_sales_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);

INSERT INTO products (name, category, price, quantity)
SELECT 'Floral Rayon Kurti', 'Kurtis', 1299, 40 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Floral Rayon Kurti');

INSERT INTO products (name, category, price, quantity)
SELECT 'Banarasi Saree', 'Sarees', 2499, 18 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Banarasi Saree');

INSERT INTO products (name, category, price, quantity)
SELECT 'Cotton Leggings', 'Leggings', 499, 55 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Cotton Leggings');

INSERT INTO products (name, category, price, quantity)
SELECT 'Printed Dupatta', 'Dupattas', 699, 9 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Printed Dupatta');

INSERT INTO sales (product_id, quantity, sale_date, total_amount)
SELECT product_id, 3, SYSDATE - 2, price * 3
FROM products
WHERE name = 'Floral Rayon Kurti'
  AND NOT EXISTS (SELECT 1 FROM sales WHERE product_id = products.product_id AND quantity = 3);

CREATE TABLE admin_requests (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(150) NOT NULL,
    email VARCHAR2(150) NOT NULL,
    username VARCHAR2(100),
    reason VARCHAR2(2000) NOT NULL,
    business_name VARCHAR2(150),
    proof VARCHAR2(2000),
    proof_file_path VARCHAR2(400),
    status VARCHAR2(30) DEFAULT 'pending' NOT NULL,
    reviewed_by NUMBER,
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_access_codes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id NUMBER,
    email VARCHAR2(150) NOT NULL,
    code VARCHAR2(20) NOT NULL UNIQUE,
    status VARCHAR2(30) DEFAULT 'active' NOT NULL,
    expires_at TIMESTAMP,
    used_at TIMESTAMP,
    generated_by NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
